### ISSUE TITLE
[Knowledge-Lingling] UI

### ISSUE THREAD

**Issue by Bug9Best** [Bug9Best/event-horizon-telescope#8]
หน้าความรู้
- Backgound
- Sound Track
- เนื้อหาของกล้องทั้ง 8 ตัว พร้อมรูปภาพ
- ปุ่มเปลี่ยนหน้า พอสุดท้ายให้มีปุ่ม เล่นเเกมส์

**Comment by Bug9Best** [comment]
หน้าความรู้
- [ ] Backgound
- [ ] Sound Track
- [ ] เนื้อหาของกล้องทั้ง 8 ตัว พร้อมรูปภาพ
- [ ] ปุ่มเปลี่ยนหน้า พอสุดท้ายให้มีปุ่ม เล่นเเกมส์

**Comment by Bug9Best** [comment]
หน้าความรู้

- [ ] Backgound
- [ ] Sound Track
- [ ] เนื้อหาของกล้องทั้ง 8 ตัว พร้อมรูปภาพ
- [ ] ปุ่มเปลี่ยนหน้า พอสุดท้ายให้มีปุ่ม เล่นเเกมส์

**Comment by llPornpilin** [comment]
หน้าความรู้

- [ ] Backgound
- [ ] Sound Track
- [ ] เนื้อหาของกล้องทั้ง 8 ตัว พร้อมรูปภาพ
- [ ] ปุ่มเปลี่ยนหน้า พอสุดท้ายให้มีปุ่ม เล่นเเกมส์
